contacus:
    resource: "@ContacusBundle/Resources/config/routing.yml"
    prefix:   /contact
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Admin

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /Shop

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /Blog
eventment:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /eventment
location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /location
EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Resources/config/routing.yml"
    prefix:   /qrcode
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"